baseURL = "https://twotone-fcafb.web.app/"
disableLanguages = ["fr"]
disqusShortname = "twotone"
paginate = "6"
summaryLength = "10"
theme = "agico-hugo"
title = "TwoTone | Technical Support"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About us"
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact us"
[[Languages.en.menu.footer]]
URL = "https://www.freeprivacypolicy.com/live/a571745a-96df-4b8a-8dfb-ef3342496cc6"
name = "Terms and Conditions"
[[Languages.en.menu.footer]]
URL = "https://www.freeprivacypolicy.com/live/1dbfbe3f-6f52-450f-acb1-dae293f06159"
name = "Privacy Policy"
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "service"
name = "Service"
weight = 3
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[Languages.en.menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "about"
name = "Company History"
[[Languages.fr.menu.footer]]
URL = "about"
name = "About us"
[[Languages.fr.menu.footer]]
URL = "contact"
name = "Contact us"
[[Languages.fr.menu.footer]]
URL = "service"
name = "Services"
[[Languages.fr.menu.footer]]
URL = "#"
name = "Privacy Policy"
[[Languages.fr.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.fr.menu.main]]
URL = "service"
name = "Service"
weight = 3
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 6
[[Languages.fr.menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "career"
name = "Career"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "team"
name = "Team"
parent = "Pages"
[params]
address = ""
author = "DropByte | Themefisher"
contact_form_action = "#"
description = "Need support? Contact us!"
email = "help@twotonesupport.com"
google_analitycs_id = "Your ID"
logo = "images/logo.png"
mobile = "(865) 830-9504"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
map_marker_label = "Agico"
map_zoom = 17
[params.navigation_button]
enable = true
label = "sign in"
link = "https://subscriptions.zoho.com/portal/twotonetechmanagement/login"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/font-awesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "fa-facebook"
link = "https://www.facebook.com/TwoToneSupport"
[[params.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/twotonesupport/"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/twotonesupport"
